### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by padraigmc** [dylank09/CS4141project#5]
Add "void" to your first method in the mainClass on line 10.
Now - `public mainClassProj(int capacity) {`
With change - `public void mainClassProj(int capacity) {`

**Comment by dylank09** [comment]
ok. why?

**Comment by dylank09** [comment]
void means no return, but the ListClassExample doesnt have a void there at all

**Comment by padraigmc** [comment]
You're right my bad, that's a constructor. I think it does whatever's in the body of it by default. So in the driver when we make our instance of the mainClassProj:

`mainClassProj driver;
 driver = new mainClassProj();`
It will automatically set the first three indices as Sheet 1 2 and 3, which is what we want

> Yurt
      - Abraham Lincoln

**Comment by dylank09** [comment]
Ok.
Regards Dylan

"Yurt"- Bill Jobs
